package com.lbt.telegram_learning_bot.bot;

// BotState.java
public enum BotState {
    MAIN_MENU,
    MY_COURSES,
    ALL_COURSES,
    SEARCH_COURSES,
    AWAITING_SEARCH_QUERY,
    COURSE_SECTIONS,
    SECTION_TOPICS,
    TOPIC_BLOCKS,
    TOPIC_LEARNING,      // <-- новое состояние
    BLOCK_CONTENT,
    QUESTION,
    TEST_RESULT,
    // административные
    ADMIN_MENU,
    AWAITING_COURSE_JSON,
    AWAITING_IMAGE,
    AWAITING_COURSE_SELECTION_FOR_EDIT,
    AWAITING_SECTION_SELECTION_FOR_EDIT,
    AWAITING_TOPIC_SELECTION_FOR_EDIT,
    EDIT_COURSE_NAME_DESC,
    EDIT_SECTION_NAME_DESC,
    EDIT_TOPIC_JSON,
    AWAITING_COURSE_SELECTION_FOR_DELETE,
    EDIT_COURSE_CHOOSE_ACTION,
    EDIT_COURSE_SECTION_CHOOSE,
    EDIT_SECTION_CHOOSE_TOPIC,
    AWAITING_IMAGES,
}